### ISSUE TITLE
Add new endpoint (device type and manufacturer)

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/lookups-api#9]
1. Develop endpoint DeviceType which will return all device type in the form of array.
GET /v5/lookups/devices/types
Response : return unique list of device types as string
[ "Desktop",
    "Laptop",
    “Mobile”,
    "Console”
]
2. Develop endpoint manufacturer  which will take parameter deviceType, and based on the device type it will return all manufacturer . 
GET /v5/lookups/devices/manufacturers?type=<mobile>
[   "Acer",
    "Apple",
    “Samsung”,
    "Console”
]

**Comment by callmekatootie** [comment]
Both endpoints are now in. Closing ticket.
